import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"

import Header from '@/components/Header'
import React from 'react'

const inter = Kumbh_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "DevJobs | Job Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={`${inter.className} `}>
        <div className='bg-[#f2f2f2] min-h-screen'>
          <Header />

          {children}
          <Toaster />
        </div>
      </body>
    </html>
  );
}
